### ISSUE TITLE
CryoTEMPO - Create global region code values

### ISSUE THREAD

**Issue by shendric** [pysiral/pysiral#113]
Region code values for the northern and southern hemisphere are currently ambiguous, as both start at 1. For output like CryoTEMPO it is desirable to remove this ambiguity. 

Note: Since of the NSIDC region code version 2021, there are no longer flag values for `land` or `land_outline`. Codes for the southern hemisphere are also sector based and to not include a land mask. Therefore, the value 100 is added to the southern hemisphere code to leave a buffer of sufficient size between the codes for sea ice regions in the northern and southern hemisphere.

| Flag Value | Flag Meaning |
| ---------- | ------------ |
| 0 |  Undefined_Region |
| 1 |  Central_Arctic | 
| 2 |  Beaufort_Sea | 
| 3 |  Chukchi_Sea |
| 4 |  East_Siberian_Sea |
| 5 |  Laptev_Sea |
| 6 |  Kara_Sea |
| 7 |  Barents_Sea |
| 8 |  East_Greenland_Sea |
| 9 |  Baffin_Bay_&_Labrador_Sea |
| 10 |  Gulf_of_St_Lawrence |
| 11 |  Hudson_Bay |
| 12 |  Canadian_Archipelago |
| 13 |  Bering_Sea |
| 14 |  Sea_of_Okhotsk |
| 15 |  Sea_of_Japan |
| 16 |  Bohai_Sea |
| 17 |  Baltic_Sea |
| 18 |  Gulf_of_Alaska |
| 100 |  Indian_Ocean |
| 101 |  Western_Pacific_Ocean |
| 102 |  Ross_Sea |
| 103 |  Bellingshausen_Amundsen_Seas |
| 104 |  Weddell_Sea |

**Comment by shendric** [comment]
The attribute of the variable `region_code` should include:

```yaml
  region_code:
    long_name: "region code"
    unit: 1
    comment: "Source: Northern hemisphere: A new regional mask for Arctic sea ice trends and climatologies (J. Scott Stewart and Walter N. Meier, NSIDC), Southern hemisphere: longitude sectors south of 40S (Parkinson, C. L. and Cavalieri, D. J. 2012)"
    valid_min: 0
    valid_max: 104
    flag_meanings: "Undefined_Region Central_Arctic Beaufort_Sea Chukchi_Sea East_Siberian_Sea  Laptev_Sea Kara_Sea Barents_Sea East_Greenland_Sea Baffin_Bay_&_Labrador_Sea Gulf_of_St_Lawrence Hudson_Bay Canadian_Archipelago Bering_Sea Sea_of_Okhotsk Sea_of_Japan Bohai_Sea Baltic_Sea Gulf_of_Alaska Indian_Ocean Western_Pacific_Ocean, Ross_Sea Bellingshausen_Amundsen_Seas Weddell_Sea"
    flag_values: "0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 100, 101, 102, 103, 104"
    units: "1"
    coordinates: "time"
    coverage_content_type: referenceInformation
```
