### ISSUE TITLE
Incorrect interpolation of filtered sea level anomalies over land

### ISSUE THREAD

**Issue by shendric** [pysiral/pysiral#120]
**Problem**

The sea level anomaly smoothed with a lowess filter incorrectly interpolates sea level anomaly values over land: 

![param_sea_level_anomaly_arctic_wide_sin 1280](https://github.com/pysiral/pysiral/assets/10025761/143901c8-b340-4de4-a286-97422526be8a)

**Intended Solution**

The class [pysiral.filter.ParameterSmoother](https://github.com/pysiral/pysiral/blob/aea609c9661789c656459b99ad5488a16e2317d0/pysiral/filter.py#L149) needs an optional valid mask, because in the current implementation the smoother does not know which waveform is over land.

**Comment by djbwork** [comment]
What about adding a general class at the end of the chain to manipulate values based on other values? Something like:
 
```
   -   module: filter
        pyclass: L2ParameterModifier
        options:
            test_variable: surface_type
            test_condition: "== 'land'"
            target_variables: [sla, slaflt]
            set_to: nan
```
