### ISSUE TITLE
CryoTEMPO SI.8/PO.8 - Addition of region ID’s for Arctic Ocean. 

### ISSUE THREAD

**Issue by shendric** [pysiral/pysiral#69]
Add a flag indicating Arctic Ocean region in the l2 output

**Comment by shendric** [comment]
This capability is already in pysiral. The following steps are needed to write region id's to l2 output. 

1. Download [region mask netCDF file](ftp://ftp.awi.de/sea_ice/auxiliary/mask/regions_nsidc/region_mask_nsidc_adapted_v1p0.nc) and store on local production system
2. Add entry `root.auxiliary_repository.mask.region_nsidc` to `local_machine_def.yaml` pointing to the directory where the region netCDF file is stored. 
3. Add the following entry in the Level-2 processor definition:

```yaml
auxdata:

    - region:
        name: nsidc_mod
        options: null
```

4. Add the following entry to the Level-2 output definition: 

```yaml
  region_code:
    long_name: "Region code (adapted from NSIDC region mask)"
    comment: "Added flag for Baltic Sea (flag value 16)"
    valid_min: 0
    valid_max: 21
    flag_values: "0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 20, 21"
    flag_meanings: "inland_sea_and_lakes ice_free_oceans sea_of_okhotsk bering hudson_bay st_john 
    baffin_bay east_greenland_sea barents_sea kara_sea laptev_sea east_siberian_sea chukchi_sea beaufort_sea canadian_islands central_arctic valtic_sea land land_outline"
    units: 1
    coordinates: time
```

**Comment by djbwork** [comment]
Does this also need a _FillValue for areas outside the mask? What would this currently be set to at a location within Antarctic sea ice?

**Comment by shendric** [comment]
The mask file can be downloaded here: 

ftp://ftp.awi.de/sea_ice/auxiliary/mask/regions_nsidc/region_mask_nsidc_adapted_v1p0.nc

And good point with the _FillValue. I need to check the spatial extent of the mask vs. the CryoTEMPO latitude threshold. If there is full coverage the flags `inland_sea_and_lakes` `ice_free_oceans` `land` & `land_outline` should make a fill value (-1 for signed int) not necessary. 

The region id is also applied in the Level-2 processor, therefore only be used for the subsection. For the southern hemisphere I have used[ longitude based sectors](https://github.com/shendric/pysiral/blob/87723d073a3d080941028874fa1a3fb691befdf2/pysiral/resources/pysiral-cfg/auxdata_def.yaml#L761)  before.

**Comment by shendric** [comment]
Just figured that there has been an update in the region id mask that I have been using ([A new regional mask for Arctic sea ice trends and climatologies](
https://insidecires.colorado.edu/rendezvous/uploads/Rendezvous_2021_1448_1619668996.pdf)).

The mask is available as [netCDF file](https://masie_web.apps.nsidc.org/pub/DATASETS/NOAA/G02186/ancillary/) at a resolution of 4 km, which is an improvement in resolution over the existing mask. The netCDF also contains a land mask which can serve as a low-cost solution to #70

**Comment by shendric** [comment]
Gridded versions on the standard EASE2 grid of the 2021 regional mask for Arctic Sea Ice from NSIDC have been produced from the source shape file that was kindly provided for this project. The versions differ in spatial resolution (1, 3.125, 6.25, 12.5, 25, 50, & 75 km) and are publically available on the ftp server of AWI: 

ftp://ftp.awi.de/sea_ice/auxiliary/mask/regions_nsidc_2021

The grids contain the id's of each sea for the full polygon shape to keep the region id independent of the land/ocean flag: 

![region_id_in_nsidc_arctic_region_mask_2021](https://user-images.githubusercontent.com/10025761/179189760-acf6ffff-d20f-499f-ab20-68eb1c65f2bd.png)


| Region ID | Region Name                                  |
|------------|---------------------------------------|
| 0              | Undefined                                        |
| 1              | Central_Arctic                                  |
| 2              | Beaufort_Sea                                   |
| 3              | Chukchi_Sea                                    |
| 4              | East_Siberian_Sea                            |
| 5              | Laptev_Sea                                      |
| 6              | Kara_Sea                                          |
| 7              | Barents_Sea                                     |
| 8              | East_Greenland_Sea                        |
| 9              | Baffin_Bay_&_Labrador_Sea            |
| 10            | Gulf_of_St._Lawrence Hudson_Bay |
| 11            | Hudson_Bay                                    |
| 12            | Canadian_Archipelago                    |
| 13            | Bering_Sea                                      |
| 14            | Sea_of_Okhotsk                              |
| 15            | Sea_of_Japan                                  |
| 16            | Bohai_Sea                                       |
| 17            | Baltic_Sea                                       |
| 18            | Gulf_of_Alaska                                |

**Comment by shendric** [comment]
As of 6928a9763d3ba6f805a108522d2c037fad0c7e79, the new NSIDC Arctic Region Mask can be used in the Level-2 processor. The underlying netCDF is region id grid at a resolution of 1km. 

Enabling new region mask in Level-2 processor definition: 

```yaml
  auxdata:
      - region:
            name: nsidc_2021
            options: null
```

Metadata for the Level-2 output definition: 

```yaml
  region_code:
      long_name: "region id"
      unit: 1
      valid_min: 0
      valid_max: 18
      flag_meanings = "Undefined_Region Central_Arctic Beaufort_Sea Chukchi_Sea East_Siberian_Sea Laptev_Sea Kara_Sea Barents_Sea East_Greenland_Sea Baffin_Bay_&_Labrador_Sea Gulf_of_St._Lawrence Hudson_Bay Canadian_Archipelago Bering_Sea Sea_of_Okhotsk Sea_of_Japan Bohai_Sea Baltic_Sea Gulf_of_Alaska"
      flag_values: "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18"
      comment: "Adapted from "A new regional mask for Arctic sea ice trends and climatologies (J. Scott Stewart and Walter N. Meier, NSIDC)"
      coordinates: time
```
