### ISSUE TITLE
CryoTEMPO SI.11/PO.7 - use of DAC instead of IB correction to remove high frequency variation on shelf areas

### ISSUE THREAD

**Issue by shendric** [pysiral/pysiral#72]
Replace the inverse barometric correction with the dynamic atmosphere correction

**Comment by shendric** [comment]
This step requires modifying the options from two l2 processor steps:

1. Add `dynamic_transfer` to the list of variable that are transferred from the l1p to the l2 data object:

```yaml
    -   module: l2proc.procsteps
        pyclass: L1BL2TransferVariables
        options: 
            ...
            correction:
                dry_troposphere: [rcdt, dry_troposphere]
                wet_troposphere: [rcwt, wet_troposphere]
                inverse_barometric: [rcib, inverse_barometric]
++              dynamic_atmosphere: [rdac, dynamic_atmosphere]
                ionosphere: [rcio, ionosphere]
                ocean_tide_elastic: [rcote, ocean_tide_elastic]
                ocean_tide_long_period: [rcotlp, ocean_tide_long_period]
                ocean_loading_tide: [rcolt, ocean_loading_tide]
                solid_earth_tide: [rcset, solid_earth_tide]
                geocentric_polar_tide: [rcgpt,  geocentric_polar_tide]
```

2. Replace `inverse_barometric` with `dynamic_atmosphere` in the list of range corrections: 

```yaml
    # Apply the range corrections 
    -   module: l2proc.procsteps
        pyclass: L2ApplyRangeCorrections
        options:
            corrections: 
                - dry_troposphere
                - wet_troposphere
--              - inverse_barometric
++              - dynamic_atmosphere
                - ionosphere
                - ocean_tide_elastic
                - ocean_tide_long_period
                - ocean_loading_tide
                - solid_earth_tide
                - geocentric_polar_tide
```
