### ISSUE TITLE
CryoTEMPO SI.13/PO.5 - Add LRM and merge with SAR/SIN data

### ISSUE THREAD

**Issue by shendric** [pysiral/pysiral#73]
Ingest IPF-d/e LRM data and merge with other radar modes

**Comment by shendric** [comment]
The functionality is already on pysiral and the following steps are needed to activate the option in the Level-1 pre-processor. 

1. Download CryoSat-2 LRM baseline-E data and store on local production system 
2. Add an `lrm` entry to the `sar`/`sin` directories for baseline-d/e data, e.g.:

```yaml
l1b_repository:

    # CryoSat-2
    cryosat2:

        # Baseline-D OFFL reprocessed data
        baseline_d:
            source:
                sar: /isibhv/platforms/satellite/cs2/siral/ipf1-d/l1b-offl/sar/data/
                sin: /isibhv/platforms/satellite/cs2/siral/ipf1-d/l1b-offl/sin/data/
++              lrm: /isibhv/platforms/satellite/cs2/siral/ipf1-d/l1b-offl/lrm/data/
            l1p: /isibhv/projects/siral/data/altimetry/cryosat2/ipf1-d/rep/l1p/
```

2. Add `lrm` to the list of radar modes in the input handler of the Level-1 pre-processor settings: 

```yaml
input_handler:
    
    module_name: pysiral.cryosat2.iotools
    class_name: BaselineDFileDiscovery
    
    options:
        local_machine_def_tag: baseline_d  # -> l1b_repository.$platform.$input_tag in (local_machine_def.yaml)
        lookup_dir: null  # Leave emtpy: This will be automatically filled with information from local_machine_def
->      lookup_modes: [lrm, sar, sin]
        filename_search: CS_*_SIR_*1B_{year:04d}{month:02d}{day:02d}*_D*.nc
        filename_sep: _   # character to split the filename
        tcs_str_index: 5  # index of time_coverage_start string in file (when splitting filename with filename_sep)
```

3. Add the pre-processor item "Pad LRM waveforms". This item will padd the LRM waveforms to 256 range bins to allow merging with SAR and (cropped) SIN waveform arrays. 

```yaml
        pre_processing_items:
            
            # Resample SIN waveforms to the same size as SAR waveforms
            # NOTE: This will only have an effect of SIN segments
            - label: "Resample SIN waveforms"
              module_name: pysiral.cryosat2.functions
              class_name: L1PWaveformResampleSIN
              options:
                  sin_target_bins: 256

            # Pad LRM waveforms to the same size as SAR waveforms
            # NOTE: This will only have an effect of LRM segments
            - label: "Pad LRM waveforms"
              module_name: pysiral.cryosat2.functions
              class_name: L1PWaveformPadLRM
              options:
                  lrm_target_bins: 256
```

4. Add new sigma0 computation pre-processor item:

```yaml
            # Compute waveform backscatter coeficient (sigma0)
            - label: "Compute Sigma0"
              module_name: pysiral.waveform
              class_name: L1PSigma0
              options:

                  # CryoSat-2 altimeter constants to compute the LRM footprint
                  footprint_pl_kwargs:
                      band_width: 320000000.

                  # CryoSat-2 altimeter constants to compute the SAR footprint
                  footprint_sar_kwargs: 
                      ptr_width: 2.819e-09
                      tau_b: 0.00352
                      lambda_0: 0.022084
                      wf: 1.0
                 
                  # CryoSat-2 altimeter constants to compute sigma0
                  sigma0_kwargs:
                      lambda_0: 0.022084
                      g_0: 19054.607179632483

                  # CryoSat-2 radar mode sigma0 biases
                  sigma0_bias: [0.0, 0.0, 0.0]
```
